# Generated by Django 5.1 on 2024-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HookLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Hey, would you like to buy me a wine?', help_text="Hook line should be an interesting paragraph, fact, or a question to cath audience's attention.", max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Hook Lines',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Full Name')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('message', models.TextField(max_length=10000, verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='MetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Send me a token of your love and gratitude with wine and a personalized message!', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Meta Descriptions',
            },
        ),
    ]
