# Generated by Django 5.1 on 2024-08-14 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelPageMetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Your donation was cancelled. If you have any questions or would like to try again, please contact me.', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Cancel Page Meta Descriptions',
            },
        ),
        migrations.CreateModel(
            name='SuccessPageMetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Thank you for your donation! Your support means the world to me.', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Success Page Meta Descriptions',
            },
        ),
        migrations.RenameModel(
            old_name='HookLine',
            new_name='HomePageHookLine',
        ),
        migrations.RenameModel(
            old_name='MetaDescription',
            new_name='HomePageMetaDescription',
        ),
        migrations.AlterModelOptions(
            name='homepagehookline',
            options={'verbose_name_plural': 'Home Page Hook Lines'},
        ),
        migrations.AlterModelOptions(
            name='homepagemetadescription',
            options={'verbose_name_plural': 'Home Page Meta Descriptions'},
        ),
        migrations.AddField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Send Time'),
        ),
    ]
