# Generated by Django 5.1 on 2024-08-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_store', '0002_cancelpagemetadescription_successpagemetadescription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelPageMetaDescription',
        ),
        migrations.DeleteModel(
            name='SuccessPageMetaDescription',
        ),
    ]
